### ISSUE TITLE
Savepoint error

### ISSUE THREAD

**Issue by RodionF** [rberzh/cec-incident-sender#1]
После отправки одного инцидента сбор данных завершается с ошибкой. 

can't send savepoint: incorrect format"},"time":1702286288995,"status":"error

**Comment by rberzh** [comment]
> После отправки одного инцидента сбор данных завершается с ошибкой.
> 
> can't send savepoint: incorrect format"},"time":1702286288995,"status":"error

Исправлено, спасибо за репорт!
